package com.example.leon.article.sql.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.leon.article.sql.bean.Arts;

import com.example.leon.article.sql.bean.ArtsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig artsDaoConfig;

    private final ArtsDao artsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        artsDaoConfig = daoConfigMap.get(ArtsDao.class).clone();
        artsDaoConfig.initIdentityScope(type);

        artsDao = new ArtsDao(artsDaoConfig, this);

        registerDao(Arts.class, artsDao);
    }
    
    public void clear() {
        artsDaoConfig.clearIdentityScope();
    }

    public ArtsDao getArtsDao() {
        return artsDao;
    }

}
